### ISSUE TITLE
Fields missing for deserializing order::Order from response of order_capture

### ISSUE THREAD

**Issue by fsgmhoward** [edg-l/paypal-rs#1]
I am currently using 0.2.0-alpha.3 for my app as I am using tokio 1.x runtime. I encountered the problem of missing fields (which caused it to panic) when using `Client::order_capture`. I tried to check the code and PayPal's docs and found that:

1. `Capture` does not necessary have a field `status_details` and it seems to appear only when status is `PENDING`, so it should probably be like:
```
pub struct Capture {
    /// The status of the captured payment.
    pub status: CaptureStatus,
    /// The details of the captured payment status.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status_details: Option<CaptureStatusDetails>,
}
```

2. For `PaymentCollection` not all kind of collection appears, so it should have `serde(default)` to handle missing fields. For instance, order_capture has only captures in return when I did my testing. Changing it to this works:
```
pub struct PaymentCollection {
    /// An array of authorized payments for a purchase unit. A purchase unit can have zero or more authorized payments.
    #[serde(default)]
    pub authorizations: Vec<AuthorizationWithData>,
    /// An array of captured payments for a purchase unit. A purchase unit can have zero or more captured payments.
    #[serde(default)]
    pub captures: Vec<Capture>,
    /// An array of refunds for a purchase unit. A purchase unit can have zero or more refunds.
    #[serde(default)]
    pub refunds: Vec<Refund>,
}
```

Much appreciated for all your works that have been done! Probably there are more cases like this to be fixed and not being discovered yet.

**Comment by edg-l** [comment]
Feel free to contribute and fix it, otherwise i'll try to do it when I have some time.

**Comment by edg-l** [comment]
Ok this is a quick fix so I did it, it's true that its hard to know when something is optional or not due to the paypal docs not being really explicit about it...
